clone_folder: C:\repo

# Do not build feature branches that are already built as part of a pull request.
skip_branch_with_pr: true

matrix:
  fast_finish: true

environment:
  global:
    DOWNLOAD_DIR: _download_cache
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\Git\cmd;C:\Tools\curl\bin;C:\msys64\usr\bin;C:\Program Files\7-zip;C:\Program Files (x86)\Inno Setup 5
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VER: "14"
      PLATFORM: "x86"
      PYTHON: C:\Python36\python.exe

build_script:
  - "%PYTHON% --version"
  # Print PATH variable.
  - set PATH
  - for /f %%i in ('%PYTHON% -c "from rednotebook import info; print(info.version)"') do set VERSION=%%i
  - set VERSION
  - cd win

  # Set up GTK stack.
  - curl -Lo gtk.tar.gz https://www.dropbox.com/s/94013wl3qud8rr5/gvsbuild-vs14-x86-2020-05-adwaita.tar.gz?dl=1
  - tar -xzf gtk.tar.gz
  - move release C:\gtk
  - set PATH=%PATH%;C:\gtk\bin

  # Install other dependencies.
  - "%PYTHON% -m pip install -U pip wheel"
  - "%PYTHON% -m pip install -r requirements.txt"
  - "%PYTHON% -m pip install C:/gtk/python/pycairo-1.19.1-cp36-cp36m-win32.whl C:/gtk/python/PyGObject-3.36.0-cp36-cp36m-win32.whl"
  - "%PYTHON% -m pip freeze"
  - "%PYTHON% -m pip list --outdated"

  # Pyenchant wheels bundle DLLs. The bundled DLLs are incompatible to the
  # DLLs we use and lead to the error "ImportError: DLL load failed: The
  # specified procedure could not be found." when calling "import gi".
  # Therefore, we use the --no-binary option when installing the pyenchant
  # package and put our own DLLs in the
  # places where pyenchant and PyInstaller expect them
  # (see also https://pyenchant.github.io/pyenchant/install.html)
  # We currently pin pyenchant to version 2.0 since later versions moved
  # things around and making them work proved difficult. We might want to
  # try again once we need to support newer enchant versions.
  - set PYENCHANT_VERBOSE_FIND=foobar
  - rm C:/Python36/Lib/site-packages/enchant/*.dll
  - rm C:/Python36/Lib/site-packages/enchant/lib/enchant/*.dll
  - cp C:/gtk/bin/libenchant.dll C:/Python36/Lib/site-packages/enchant
  #- mkdir C:\Python36\Lib\site-packages\enchant\lib\enchant\
  - cp C:/gtk/lib/enchant/libenchant_*.dll C:/Python36/Lib/site-packages/enchant/lib/enchant/

  # Remove bundled dictionaries and install custom ones.
  - curl -Lo dicts.tar.gz https://www.dropbox.com/s/f12k20aur6znpmo/myspell-dicts.tar.gz?dl=1
  - tar -xzf dicts.tar.gz
  #- mkdir C:\Python36\Lib\site-packages\enchant\share
  #- move enchant C:\Python36\Lib\site-packages\enchant\share

  # Sanity check with dummy app.
  - "%PYTHON% sampleapp.py"
  - "%PYTHON% -m PyInstaller --debug=all --additional-hooks-dir=. sampleapp.py"
  # Use clean PATH to check that everything has been copied correctly.
  - cmd /C "set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem && dist\sampleapp\sampleapp.exe"

  # Create executable.
  - "%PYTHON% -m PyInstaller --workpath=C:/build --distpath=C:/ rednotebook.spec"
  - "%PYTHON% build-translations.py C:/dist/share/locale"
  - tar -czf rednotebook.tar.gz -C /c/ dist
  - 7z a rednotebook.zip C:\dist

  # Build installer.
  - iscc /Qp /dREDNOTEBOOK_VERSION="%VERSION%" rednotebook.iss

  # Artifacts have to live under "clone_folder".
  - move rednotebook.tar.gz C:\repo\rednotebook-"%VERSION%".tar.gz
  - move rednotebook.zip C:\repo\rednotebook-"%VERSION%".zip
  - move C:\rednotebook.exe C:\repo\rednotebook-"%VERSION%".exe

artifacts:
  - path: rednotebook-*.tar.gz
    name: Standalone Windows executable (tarball)
  - path: rednotebook-*.zip
    name: Standalone Windows executable (zipfile)
  - path: rednotebook-*.exe
    name: Windows installer

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: "UT6jPkpy8U/qTN+8LF7hPsJ/cHWlt+7a+wO2Ou2iKYImeBxAV4OY6Gt3Y0v5/ZuL"
  artifact: /rednotebook-.*\.exe/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

cache:
  - '%DOWNLOAD_DIR%'

test: off
