clone_folder: C:\repo

matrix:
  fast_finish: true

environment:
  global:
    DOWNLOAD_DIR: _download_cache
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\Git\cmd;C:\Tools\curl\bin;C:\msys64\usr\bin;C:\Program Files\7-zip;C:\Program Files (x86)\Inno Setup 5
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      VS_VER: 14
      PLATFORM: x64
      PYTHON: C:\Python39-x64\python.exe

build_script:
  - "%PYTHON% --version"
  - set PATH  # Print PATH variable.
  - for /f %%i in ('%PYTHON% -c "from rednotebook import info; print(info.version)"') do set VERSION=%%i
  - set VERSION
  - cd win

  - '%PYTHON% -c "import platform; print(platform.architecture())"'

  # Set up GTK stack compiled with gvsbuild.
  - curl -Lo gtk-bundle.zip https://www.dropbox.com/s/lo0p8c96cljcc1c/gtk-bundle.zip?dl=1
  - 7z x gtk-bundle.zip -oC:\gtk
  - dir C:\gtk
  - set PATH=%PATH%;C:\gtk\bin

  # Install other dependencies.
  - "%PYTHON% -m pip install --no-warn-script-location -U pip setuptools wheel"
  # Install separately because --no-binary options disables using wheels (leading to problems for Cython).
  - "%PYTHON% -m pip install --no-warn-script-location -U --no-binary :all: pyenchant==3.2.2"
  - "%PYTHON% -m pip install --no-warn-script-location -r requirements.txt"
  - "%PYTHON% -m pip install --no-warn-script-location C:/gtk/pycairo-1.21.0-cp39-cp39-win_amd64.whl C:/gtk/PyGObject-3.42.0-cp39-cp39-win_amd64.whl"
  - "%PYTHON% -m pip freeze"
  - "%PYTHON% -m pip list --outdated"

  # Patch GtkSourceView hook by replacing "3.0" with "4".
  - sed -i 's/3\.0/4/g' C:/Python39-x64/Lib/site-packages/pyinstaller/hooks/hook-gi.repository.GtkSource.py

  # Pyenchant wheels bundle DLLs. The bundled DLLs are incompatible to the
  # DLLs we use and lead to the error "ImportError: DLL load failed: The
  # specified procedure could not be found." when calling "import gi".
  # Therefore, we use the --no-binary option when installing the pyenchant
  # package and put our own DLLs in the
  # places where pyenchant and PyInstaller expect them
  # (see also https://pyenchant.github.io/pyenchant/install.html)
  - set PYENCHANT_VERBOSE_FIND=foobar
  #- cp C:/gtk/bin/libenchant.dll C:/Python39-x64/Lib/site-packages/enchant/
  # TODO: needed?
  #- mkdir C:\Python39-x64\Lib\site-packages\enchant\lib\enchant\
  #- cp C:/gtk/lib/enchant/libenchant_*.dll C:/Python39-x64/Lib/site-packages/enchant/lib/enchant/

  # Remove bundled dictionaries and install custom ones.
  - curl -Lo dicts.tar.gz https://www.dropbox.com/s/f12k20aur6znpmo/myspell-dicts.tar.gz?dl=1
  - tar -xzf dicts.tar.gz
  - move enchant C:\gtk\share

  # Sanity check with dummy app. Pyinstaller misses libenchant.dll, so we manually add it to ".".
  - "%PYTHON% sampleapp.py"
  - "%PYTHON% -m PyInstaller --debug=all --additional-hooks-dir=. --add-data C:/gtk/bin/libenchant.dll;. sampleapp.py"
  - echo Exit Code A is %errorlevel%
  # Use clean PATH to check that everything has been copied correctly.
  - cmd /C "set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem && dist\sampleapp\sampleapp.exe"
  - echo Exit Code B is %errorlevel%

  # Create executable.
  - "%PYTHON% -m PyInstaller --workpath=C:/build --distpath=C:/ rednotebook.spec"
  - "%PYTHON% build-translations.py C:/dist/share/locale"
  - tar -czf rednotebook.tar.gz -C /c/ dist
  - 7z a rednotebook.zip C:\dist

  # Build installer.
  - iscc /Qp /dREDNOTEBOOK_VERSION="%VERSION%" rednotebook.iss

  # Artifacts have to live under "clone_folder".
  - move rednotebook.tar.gz C:\repo\rednotebook-"%VERSION%".tar.gz
  - move rednotebook.zip C:\repo\rednotebook-"%VERSION%".zip
  - move C:\rednotebook.exe C:\repo\rednotebook-"%VERSION%".exe

artifacts:
  - path: rednotebook-*.tar.gz
    name: Standalone Windows executable (tarball)
  - path: rednotebook-*.zip
    name: Standalone Windows executable (zipfile)
  - path: rednotebook-*.exe
    name: Windows installer

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: "UT6jPkpy8U/qTN+8LF7hPsJ/cHWlt+7a+wO2Ou2iKYImeBxAV4OY6Gt3Y0v5/ZuL"
  artifact: /rednotebook-.*\.exe/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

cache:
  - '%DOWNLOAD_DIR%'

test: off
